name: Test Action

env:
  # See: https://github.com/actions/setup-node/#readme
  NODE_VERSION: 16.x

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}

    env:
      GITHUB_TOKEN: ${{ github.token }}

    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
          - windows-latest

    steps:
      - name: Disable EOL conversions
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: npm install
        run: npm install

      - name: npm lint
        run: npm run format-check

      - name: npm test
        run: npm test
